# Generated by Django 3.1 on 2020-09-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='personalnumber',
            new_name='personalNumber',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='armyposistion',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='armyunit',
            new_name='unit',
        ),
    ]
