# Generated by Django 3.1 on 2020-09-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200906_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='lastname',
            new_name='lastName',
        ),
    ]
