# Generated by Django 3.1 on 2020-09-12 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formstable',
            name='messages',
        ),
    ]
